import { Routes } from '@angular/router';
import { ConfigurationComponent } from './features/configuration/configuration.component';

export const routes: Routes = [
  {
    path: '',
    redirectTo: 'configuracion',
    pathMatch: 'full',
  },
  { path: 'configuracion', component: ConfigurationComponent },
  { path: 'entidades', loadComponent: () => import('./features/configuration/components/catalogo-entidades/catalogo-entidades').then(m => m.CatalogoEntidades) },
  { path: 'bienes-servicios', loadComponent: () => import('./features/configuration/components/catalogo-bienes-servicios/catalogo-bienes-servicios').then(m => m.CatalogoBienesServicios) },
  { path: 'presupuesto', loadComponent: () => import('./features/configuration/components/catalogo-presupuesto/catalogo-presupuesto').then(m => m.CatalogoPresupuesto) },
  { path: 'cuentas-contables', loadComponent: () => import('./features/configuration/components/catalogo-cuentas-contables/catalogo-cuentas-contables').then(m => m.CatalogoCuentasContables) },
  { path: 'bancos', loadComponent: () => import('./features/configuration/components/catalogo-bancos/catalogo-bancos').then(m => m.CatalogoBancos) },
  { path: 'ciudades-departamentos', loadComponent: () => import('./features/configuration/components/catalogo-departamento-ciudades/catalogo-departamento-ciudades').then(m => m.CatalogoDepartamentoCiudades) },
  { path: 'espacios', loadComponent: () => import('./features/configuration/components/catalogo-espacios/catalogo-espacios').then(m => m.CatalogoEspacios) },
  { path: 'unidades', loadComponent: () => import('./features/configuration/components/catalogo-unidades/catalogo-unidades').then(m => m.CatalogoUnidades) },
  { path: 'tipos-contrato', loadComponent: () => import('./features/configuration/components/catalogo-tipo-contrato/catalogo-tipo-contrato').then(m => m.CatalogoTipoContrato) },
  { path: 'modalidades-seleccion', loadComponent: () => import('./features/configuration/components/catalogo-modalidades-seleccion/catalogo-modalidades-seleccion').then(m => m.CatalogoModalidadesSeleccion) },
  { path: 'documentacion-minima', loadComponent: () => import('./features/configuration/components/catalogo-documentacion-minima/catalogo-documentacion-minima').then(m => m.CatalogoDocumentacionMinima) },
  { path: 'polizas', loadComponent: () => import('./features/configuration/components/catalogo-polizas/catalogo-polizas').then(m => m.CatalogoPolizas) },
  { path: 'informes', loadComponent: () => import('./features/configuration/components/catalogo-informes/catalogo-informes').then(m => m.CatalogoInformes) },
  { path: 'documentos', loadComponent: () => import('./features/configuration/components/catalogo-documentos/catalogo-documentos').then(m => m.CatalogoDocumentos) },
  { path: 'documentos-soporte', loadComponent: () => import('./features/configuration/components/catalogo-documento-soporte/catalogo-documento-soporte').then(m => m.CatalogoDocumentoSoporte) },
  { path: 'bienes-agrupados', loadComponent: () => import('./features/configuration/components/catalogo-bienes-agrupados/catalogo-bienes-agrupados').then(m => m.CatalogoBienesAgrupados) },
  { path: 'tipos-bienes', loadComponent: () => import('./features/configuration/components/catalogo-tipos-bienes/catalogo-tipos-bienes').then(m => m.CatalogoTiposBienes) },
  { path: 'movimientos-almacen', loadComponent: () => import('./features/configuration/components/catalogo-movimientos-almacen/catalogo-movimientos-almacen').then(m => m.CatalogoMovimientosAlmacen) },
  { path: 'tipos-procesos', loadComponent: () => import('./features/configuration/components/catalogo-tipos-procesos/catalogo-tipos-procesos').then(m => m.CatalogoTiposProcesos) },
  { path: 'impuestos', loadComponent: () => import('./features/configuration/components/catalogo-impuestos/catalogo-impuestos').then(m => m.CatalogoImpuestos) },
  { path: 'codigos-ciiu', loadComponent: () => import('./features/configuration/components/catalogo-codigos-ciiu/catalogo-codigos-ciiu').then(m => m.CatalogoCodigosCiiu) },
  { path: 'tipos-identificacion', loadComponent: () => import('./features/configuration/components/catalogo-tipos-identificacion/catalogo-tipos-identificacion').then(m => m.CatalogoTiposIdentificacion) },
  { path: 'sedes', loadComponent: () => import('./features/configuration/components/catalogo-sedes/catalogo-sedes').then(m => m.CatalogoSedes) },
  { path: 'condiciones-entrega', loadComponent: () => import('./features/configuration/components/catalogo-condiciones-entrega/catalogo-condiciones-entrega').then(m => m.CatalogoCondicionesEntrega) },
  { path: 'responsabilidades-fiscales', loadComponent: () => import('./features/configuration/components/catalogo-resposabilidades-fiscales/catalogo-resposabilidades-fiscales').then(m => m.CatalogoResposabilidadesFiscales) },
  { path: 'medios-pago', loadComponent: () => import('./features/configuration/components/catalogo-medios-pagos/catalogo-medios-pagos').then(m => m.CatalogoMediosPagos) },
  { path: 'tipos-personas', loadComponent: () => import('./features/configuration/components/catalogo-tipos-personas/catalogo-tipos-personas').then(m => m.CatalogoTiposPersonas) },
  { path: 'tipos-regimen', loadComponent: () => import('./features/configuration/components/catalogo-tipos-regimen/catalogo-tipos-regimen').then(m => m.CatalogoTiposRegimen) },
  { path: 'paises', loadComponent: () => import('./features/configuration/components/catalogo-paises/catalogo-paises').then(m => m.CatalogoPaises) },
  { path: 'justificacion-gasto', loadComponent: () => import('./features/configuration/components/catalogo-justificacion-gasto/catalogo-justificacion-gasto').then(m => m.CatalogoJustificacionGasto) },
  { path: 'fuentes-financiacion', loadComponent: () => import('./features/configuration/components/catalogo-fuentes-financiacion/catalogo-fuentes-financiacion').then(m => m.CatalogoFuentesFinanciacion) },
  { path: 'representacion', loadComponent: () => import('./features/configuration/components/catalogo-representacion/catalogo-representacion').then(m => m.CatalogoRepresentacion) },
  { path: 'actos-administrativos', loadComponent: () => import('./features/configuration/components/catalogo-actos-administrativos/catalogo-actos-administrativos').then(m => m.CatalogoActosAdministrativos) },
  { path: 'correos-institucionales', loadComponent: () => import('./features/configuration/components/catalogo-correos-institucionales/catalogo-correos-institucionales').then(m => m.CatalogoCorreosInstitucionales) },
  {
    path: '**',
    redirectTo: '',
  },
];


