import { Routes } from '@angular/router';
import { ConfigurationComponent } from './features/configuration/configuration.component';

export const routes: Routes = [
  {
    path: '',
    redirectTo: 'configuracion',
    pathMatch: 'full',
  },
  { path: 'configuracion', component: ConfigurationComponent, data: { breadcrumb: null } },
  { path: 'entidades', loadComponent: () => import('./features/configuration/components/catalogo-entidad/catalogo-entidad').then(m => m.CatalogoEntidad), data: { breadcrumb: 'Catálogo de entidades' } },
  { path: 'bienes-servicios', loadComponent: () => import('./features/configuration/components/catalogo-bienes-servicios/catalogo-bienes-servicios').then(m => m.CatalogoBienesServicios), data: { breadcrumb: 'Catálogo de bienes y servicios' } },
  { path: 'presupuesto', loadComponent: () => import('./features/configuration/components/catalogo-presupuesto/catalogo-presupuesto').then(m => m.CatalogoPresupuesto), data: { breadcrumb: 'Catálogo de presupuesto' } },
  { path: 'cuentas-contables', loadComponent: () => import('./features/configuration/components/catalogo-cuentas-contables/catalogo-cuentas-contables').then(m => m.CatalogoCuentasContables), data: { breadcrumb: 'Catálogo de cuentas contables' } },
  { path: 'bancos', loadComponent: () => import('./features/configuration/components/catalogo-bancos/catalogo-bancos').then(m => m.CatalogoBancos), data: { breadcrumb: 'Catálogo de bancos' } },
  { path: 'ciudades-departamentos', loadComponent: () => import('./features/configuration/components/catalogo-departamento-ciudades/catalogo-departamento-ciudades').then(m => m.CatalogoDepartamentoCiudades), data: { breadcrumb: 'Catálogo de ciudades y departamentos' } },
  { path: 'espacios', loadComponent: () => import('./features/configuration/components/catalogo-espacios/catalogo-espacios').then(m => m.CatalogoEspacios), data: { breadcrumb: 'Catálogo de espacios' } },
  { path: 'unidades', loadComponent: () => import('./features/configuration/components/catalogo-unidades/catalogo-unidades').then(m => m.CatalogoUnidades), data: { breadcrumb: 'Catálogo de unidades' } },
  { path: 'tipos-contrato', loadComponent: () => import('./features/configuration/components/catalogo-tipo-contrato/catalogo-tipo-contrato').then(m => m.CatalogoTipoContrato), data: { breadcrumb: 'Catálogo de tipos de contrato' } },
  { path: 'modalidades-seleccion', loadComponent: () => import('./features/configuration/components/catalogo-modalidades-seleccion/catalogo-modalidades-seleccion').then(m => m.CatalogoModalidadesSeleccion), data: { breadcrumb: 'Catálogo de modalidades de selección' } },
  { path: 'documentacion-minima', loadComponent: () => import('./features/configuration/components/catalogo-documentacion-minima/catalogo-documentacion-minima').then(m => m.CatalogoDocumentacionMinima), data: { breadcrumb: 'Catálogo de documentación mínima' } },
  { path: 'polizas', loadComponent: () => import('./features/configuration/components/catalogo-polizas/catalogo-polizas').then(m => m.CatalogoPolizas), data: { breadcrumb: 'Catálogo de pólizas' } },
  { path: 'informes', loadComponent: () => import('./features/configuration/components/catalogo-informes/catalogo-informes').then(m => m.CatalogoInformes), data: { breadcrumb: 'Catálogo de informes' } },
  { path: 'documentos', loadComponent: () => import('./features/configuration/components/catalogo-documentos/catalogo-documentos').then(m => m.CatalogoDocumentos), data: { breadcrumb: 'Catálogo de documentos' } },
  { path: 'documentos-soporte', loadComponent: () => import('./features/configuration/components/catalogo-documento-soporte/catalogo-documento-soporte').then(m => m.CatalogoDocumentoSoporte), data: { breadcrumb: 'Catálogo de documentos de soporte' } },
  { path: 'bienes-agrupados', loadComponent: () => import('./features/configuration/components/catalogo-bienes-agrupados/catalogo-bienes-agrupados').then(m => m.CatalogoBienesAgrupados), data: { breadcrumb: 'Catálogo de bienes agrupados' } },
  { path: 'tipos-bienes', loadComponent: () => import('./features/configuration/components/catalogo-tipos-bienes/catalogo-tipos-bienes').then(m => m.CatalogoTiposBienes), data: { breadcrumb: 'Catálogo de tipos de bienes' } },
  { path: 'movimientos-almacen', loadComponent: () => import('./features/configuration/components/catalogo-movimientos-almacen/catalogo-movimientos-almacen').then(m => m.CatalogoMovimientosAlmacen), data: { breadcrumb: 'Catálogo de movimientos de almacén' } },
  { path: 'tipos-procesos', loadComponent: () => import('./features/configuration/components/catalogo-tipos-procesos/catalogo-tipos-procesos').then(m => m.CatalogoTiposProcesos), data: { breadcrumb: 'Catálogo de tipos de procesos' } },
  { path: 'impuestos', loadComponent: () => import('./features/configuration/components/catalogo-impuestos/catalogo-impuestos').then(m => m.CatalogoImpuestos), data: { breadcrumb: 'Catálogo de impuestos' } },
  { path: 'codigos-ciiu', loadComponent: () => import('./features/configuration/components/catalogo-codigos-ciiu/catalogo-codigos-ciiu').then(m => m.CatalogoCodigosCiiu), data: { breadcrumb: 'Catálogo de códigos CIIU' } },
  { path: 'tipos-identificacion', loadComponent: () => import('./features/configuration/components/catalogo-tipos-identificacion/catalogo-tipos-identificacion').then(m => m.CatalogoTiposIdentificacion), data: { breadcrumb: 'Catálogo de tipos de identificación' } },
  { path: 'sedes', loadComponent: () => import('./features/configuration/components/catalogo-sedes/catalogo-sedes').then(m => m.CatalogoSedes), data: { breadcrumb: 'Catálogo de sedes' } },
  { path: 'condiciones-entrega', loadComponent: () => import('./features/configuration/components/catalogo-condiciones-entrega/catalogo-condiciones-entrega').then(m => m.CatalogoCondicionesEntrega), data: { breadcrumb: 'Condiciones de entrega' } },
  { path: 'responsabilidades-fiscales', loadComponent: () => import('./features/configuration/components/catalogo-resposabilidades-fiscales/catalogo-resposabilidades-fiscales').then(m => m.CatalogoResposabilidadesFiscales), data: { breadcrumb: 'Responsabilidades fiscales' } },
  { path: 'medios-pago', loadComponent: () => import('./features/configuration/components/catalogo-medios-pagos/catalogo-medios-pagos').then(m => m.CatalogoMediosPagos), data: { breadcrumb: 'Medios de pago' } },
  { path: 'tipos-personas', loadComponent: () => import('./features/configuration/components/catalogo-tipos-personas/catalogo-tipos-personas').then(m => m.CatalogoTiposPersonas), data: { breadcrumb: 'Tipo de personas' } },
  { path: 'tipos-regimen', loadComponent: () => import('./features/configuration/components/catalogo-tipos-regimen/catalogo-tipos-regimen').then(m => m.CatalogoTiposRegimen), data: { breadcrumb: 'Tipos de régimen' } },
  { path: 'paises', loadComponent: () => import('./features/configuration/components/catalogo-paises/catalogo-paises').then(m => m.CatalogoPaises), data: { breadcrumb: 'Catálogo de países' } },
  { path: 'justificacion-gasto', loadComponent: () => import('./features/configuration/components/catalogo-justificacion-gasto/catalogo-justificacion-gasto').then(m => m.CatalogoJustificacionGasto), data: { breadcrumb: 'Catálogo de justificación del gasto' } },
  { path: 'fuentes-financiacion', loadComponent: () => import('./features/configuration/components/catalogo-fuentes-financiacion/catalogo-fuentes-financiacion').then(m => m.CatalogoFuentesFinanciacion), data: { breadcrumb: 'Fuentes de financiación' } },
  { path: 'representacion', loadComponent: () => import('./features/configuration/components/catalogo-representacion/catalogo-representacion').then(m => m.CatalogoRepresentacion), data: { breadcrumb: 'Catálogo de representación' } },
  { path: 'actos-administrativos', loadComponent: () => import('./features/configuration/components/catalogo-actos-administrativos/catalogo-actos-administrativos').then(m => m.CatalogoActosAdministrativos), data: { breadcrumb: 'Actos administrativos' } },
  { path: 'correos-institucionales', loadComponent: () => import('./features/configuration/components/catalogo-correos-institucionales/catalogo-correos-institucionales').then(m => m.CatalogoCorreosInstitucionales), data: { breadcrumb: 'Correos institucionales' } },
  {
    path: '**',
    redirectTo: '',
  },
];


